### ISSUE TITLE
Notice Undefined offset: 1 in Line 172 SymmetricEncryptedText.module

### ISSUE THREAD

**Issue by NikoTechnik** [BitPoet/SymmetricEncryptedText#1]
When in debug mode using tracy in PW i often get an notice. 
I guess its because the  explode('|', $rawinput); in line 172 does not like having no pipe delimiter in $rawinput. 

Instead of doing
`if(! $input) return $rawinput;`
after explode , simply do a 
`if(strpos($rawinput,"|") ===false) return $rawinput;`
before.

**Comment by BitPoet** [comment]
Good catch, thank you for reporting this.

**Comment by BitPoet** [comment]
@NikoTechnik : I'm closing this issue for now. Feel free to reopen it if the fix doesn't work for you.
